### ISSUE TITLE
Add Persistent ID to Track Class

### ISSUE THREAD

**Issue by WesperBe** [asciamanna/iTunesLibraryParser#13]
The iTunes Music Library.xml file includes a "Persistent ID" for each track which allows us to find the right CoverArt in the Album Artwork directory. It would be useful if this ID would be available in the Track object. Would it be possible to add this in a next release?

**Comment by asciamanna** [comment]
Working on this now. The next version will add the Persistent ID

**Comment by asciamanna** [comment]
The latest nuget package 1.1.27 contains this update.

**Comment by WesperBe** [comment]
Thanks for updating, and sharing this project at the first place.
